### PR TITLE
Added styles

### PR DESCRIPTION
**Pull request by enjeck**
Minimal styling.

### CODE REVIEW

**Comment by Akuli** [comment]
Some thoughts:

- Can the titles be in some other font than monospace? This is a thing for mathematicians, not for programmers.
- Can the borders of the buttons be smaller, maybe 3px? They would take up less space that way.
- Can the css go into a separate file? I think that's the thing to do nowadays.

**Comment by Akuli** [comment]
BTW, speaking of space, I think the headers take up too much vertical space right now. That could also be changed.

**Comment by enjeck** [comment]
Got it.

**Comment by Akuli** [comment]
I liked #5 more. I don't mean that your thing is bad, but #5 is better in my opinion.

**Pull request closed without merging**
