### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by nikkke**
Ability to write and copy many characters

### CODE REVIEW

**Comment by Akuli** [comment]
I like this, but doesn't this mean that copying 1 character is now 2 clicks instead of just 1 click? I think this could also work so that clicking a character button puts the character to the text area *and* copies it to clipboard. Then `copy_button` would just copy the text area content to the clipboard. Of course, this needs to be explained well in the `<p>`, but I can do that if you don't want to change it.

What do you think?

**Comment by nikkke** [comment]
Better? There is also hidden button for sending text via Whatsapp. Do you want me to make that work?

**Comment by Akuli** [comment]
It works nicely now, but the code is a bit copy/pasta. Can you make `copyStringToClipboard` call `copyInputToClipboard` instead of copy/pasting the code from `copyInputToClipboard` to `copyStringToClipboard`?

**Comment by Akuli** [comment]
Oh right you also asked about the whatsapp button. If it's possible to get it to work, I'd probably like to have a separate pull request about it.

**Comment by Akuli** [comment]
nice

**Pull request merged**
